apiVersion: apps/v1
kind: Deployment
metadata:
  name: apispringdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apispringdb
  template:
    metadata:
      labels:
        app: apispringdb
    spec:
      containers:
      - name: apispringdb
        image: sshector294/apispringdb:4
        ports:
        - containerPort: 8080
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: apispringdb-svc
spec:
  selector:
    app: apispringdb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
