apiVersion: apps/v1
kind: Deployment
metadata:
  name: apispring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apispring
  template:
    metadata:
      labels:
        app: apispring
    spec:
      containers:
      - name: apispring
        image: sshector294/apispring:1
        ports:
        - containerPort: 8080
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: apispring-svc
spec:
  selector:
    app: apispring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
